targets:
  $default:
  sources:
      - swaggers/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/generated_code/"
          input_urls:
            - "https://hyperion.myecl.fr/openapi.json"
          separate_models: true