# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to App Store"
  lane :beta do |options|
    flavor = options[:flavor] # prod, alpha, dev
    app_id_prefix = options[:prefix] # fr.myecl
    app_name = options[:name] # MyECL

    api_key = app_store_connect_api_key(
      key_id: "LJN944T6G6",
      issuer_id: "8f69d502-442d-459b-a1df-84a3cb7ca7b2",
      key_filepath: "./app-store-connect-api.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    sh "flutter build ipa --dart-define-from-file=config/config-#{flavor}.json --release --flavor='#{flavor}' --export-method=app-store"

    upload_to_testflight(
      ipa: "../build/ios/ipa/#{app_name}.ipa",
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end
