import 'package:flutter/material.dart';
import 'package:myecl/tools/constants.dart';

class AMAPColorConstants extends ColorConstants {
  static final Color background = Colors.grey.shade100;
  static final Color background2 = Colors.grey.shade200;
  static final Color background3 = Colors.grey.shade300;
  static const Color greenGradient1 = Color(0xff79a400);
  static const Color greenGradient2 = Color(0xff387200);
  static const Color textDark = Color(0xff255000);
  static const Color textLight = Color(0xff528700);
  static const Color green1 = Color(0xdfa8c700);
  static const Color green2 = Color(0xdF79a400);
  static const Color enabled = Color(0xff6b9200);
  static const Color red = Color(0xFFC91717);
  static const Color redGradient1 = Color(0xFF9E131F);
  static const Color redGradient2 = Color(0xFF590512);
}

class AMAPTextConstants {
  static const String accounts = "Comptes";
  static const String add = "Ajouter";
  static const String addDelivery = "Ajouter une livraison";
  static const String addedCommand = "Commande ajoutée";
  static const String addedOrder = "Commande ajoutée";
  static const String addedProduct = "Produit ajouté";
  static const String addedUser = "Utilisateur ajouté";
  static const String addProduct = "Ajouter un produit";
  static const String addUser = "Ajouter un utilisateur";
  static const String addingACommand = "Ajouter une commande";
  static const String addingCommand = "Ajouter la commande";
  static const String addingError = "Erreur lors de l'ajout";
  static const String addingProduct = "Ajouter un produit";
  static const String admin = "Administrateur";
  static const String alreadyExistCommand =
      "Il existe déjà une commande à cette date";
  static const String amap = "Amap";
  static const String amount = "Solde";
  static const String archive = "Archiver";
  static const String archiveDelivery = "Archiver";
  static const String archivingDelivery = "Archivage de la livraison";
  static const String category = "Catégorie";
  static const String closeDelivery = "Verrouiller";
  static const String commandDate = "Date de la commande";
  static const String commandProducts = "Produits de la commande";
  static const String confirm = "Confirmer";
  static const String createCategory = "Créer une catégorie";
  static const String delete = "Supprimer";
  static const String deleteDelivery = "Supprimer la livraison ?";
  static const String deleteDeliveryDescription =
      "Cette action est irréversible";
  static const String deletedDelivery = "Livraison supprimée";
  static const String deletedOrder = "Commande supprimée";
  static const String deletedProduct = "Produit supprimé";
  static const String deleting = "Suppression";
  static const String deletingDelivery = "Supprimer la livraison ?";
  static const String deletingError = "Erreur lors de la suppression";
  static const String deletingOrder = "Supprimer la commande ?";
  static const String deletingProduct = "Supprimer le produit ?";
  static const String deliver = "Livraison teminée ?";
  static const String deliveringDelivery =
      "Toutes les commandes sont livrées ?";
  static const String delivery = "Livraison";
  static const String deliveryArchived = "Livraison archivée";
  static const String deliveryDelivered = "Livraison effectuée";
  static const String deliveryHistory = "Historique des livraisons";
  static const String deliveryList = "Liste des livraisons";
  static const String deliveryLocked = "Livraison verrouillée";
  static const String deliveryOn = "Livraison le";
  static const String deliveryOpened = "Livraison ouverte";
  static const String deliveryNotArchived = "Livraison non archivée";
  static const String deliveryNotLocked = "Livraison non verrouillée";
  static const String deliveryNotDelivered = "Livraison non effectuée";
  static const String deliveryNotOpened = "Livraison non ouverte";
  static const String editDelivery = "Modifier la livraison";
  static const String editedCommand = "Commande modifiée";
  static const String editingError = "Erreur lors de la modification";
  static const String editProduct = "Modifier le produit";
  static const String endingDelivery = "Fin de la livraison";
  static const String errorLoadingUser =
      "Erreur lors du chargement des utilisateurs";
  static const String expectingNumber = "Veuillez entrer un nombre";
  static const String fillField = "Veuillez remplir ce champ";
  static const String handlingAccount = "Gérer les comptes";
  static const String loading = "Chargement...";
  static const String lock = "Verrouiller";
  static const String locked = "Verrouillée";
  static const String lockedDelivery = "Livraison verrouillée";
  static const String lockedOrder = "Commande verrouillée";
  static const String looking = "Rechercher";
  static const String lockingDelivery = "Verrouiller la livraison ?";
  static const String myOrders = "Mes commandes";
  static const String name = "Nom";
  static const String noProduct = "Pas de produit";
  static const String noCurrentOrder = "Pas de commande en cours";
  static const String noMoney = "Pas assez d'argent";
  static const String noOpennedDelivery = "Pas de livraison ouverte";
  static const String notEnoughMoney = "Pas assez d'argent";
  static const String notPlannedDelivery = "Pas de livraison planifiée";
  static const String oneOrder = "commande";
  static const String openDelivery = "Ouvrir";
  static const String opened = "Ouverte";
  static const String openningDelivery = "Ouvrir la livraison ?";
  static const String order = "Commander";
  static const String pickChooseCategory =
      "Veuillez créer une catégorie ou en choisir une";
  static const String pickDeliveryMoment = "Choisissez un moment de livraison";
  static const String presentation = "Présentation";
  static const String price = "Prix";
  static const String product = "produit";
  static const String productInDelivery = "Produit dans la livraison";
  static const String quantity = "Quantité";
  static const String requiredDate = "La date est requise";
  static const String seeMore = "Voir plus";
  static const String the = "Le";
  static const String unlock = "Dévérouiller";
  static const String unlockedDelivery = "Livraison dévérouillée";
  static const String unlockingDelivery = "Dévérouiller la livraison ?";
  static const String update = "Modifier";
  static const String updatedAmount = "Solde modifié";
  static const String updatedOrder = "Commande modifiée";
  static const String updatedProduct = "Produit modifié";
  static const String updatingError = "Echec de la modification";
  static const String usersNotFound = "Aucun utilisateur trouvé";
  static const String waiting = "En attente";
}
