name: Build Mobile

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sign-android:
    name: Build and sign Android
    # Skip when PR from a fork
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: macos-12

    steps:
      - name: Determine ref
        id: get-ref
        run: |
          input_ref="${{ inputs.ref }}"
          github_ref="${{ github.sha }}"
          ref="${input_ref:-$github_ref}"
          echo "ref=$ref" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-ref.outputs.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: "gradle"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.6"
          cache: true

      - name: Create the Keystore
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}e
        run: echo $KEY_JKS | base64 -d > android/key.jks

      - name: Get Packages
        run: flutter pub get

      - name: Build Android App Bundle
        env:
          ALIAS: ${{ secrets.ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
        run: flutter build apk --release --no-codesign

      - name: Build ios app bundle
        run: flutter build --release --no-codesign

      - name: Publish Android & ios Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk

      
